# Location: config/redis.yml
development:
  url: redis://127.0.0.1:6379/0
test:
  url: redis://127.0.0.1:6379/15
production:
  db: 0
  uri: <%= uri = URI.parse(ENV['REDIS_URL'] || "redis://localhost:6379") %>